############################################################
#
# Notifications and groups
#
############################################################

- platform: html5
  gcm_api_key: !secret html5_gcm_api
  gcm_sender_id: !secret html5_gcm_sender
- name: trent_and_rachel
  platform: group
  services:
    - service: html5_trent_galaxys8
    - service: ios_rachels_iphone
- name: trent
  platform: group
  services:
    - service: html5_trent_galaxys8
- name: rachel
  platform: group
  services:
    - service: ios_rachels_iphone

# HASS IO Addon - Google Assistant API
- name: google_assistant_broadcast
  platform: rest
  resource: !secret ga_api_broadcast_message
- name: google_assistant_command
  platform: rest
  resource: !secret ga_api_command